In [68]:
import pandas as pd

In [69]:
weather = pd.read_csv("data_clean.csv")
weather

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

# EDA

In [70]:
weather.shape

(158, 10)

In [71]:
weather.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Day,Year,Temp
count,158.000000,120.000000,151.000000,158.000000,158.000000,158.0,158.000000
mean,79.500000,41.583333,185.403974,9.957595,16.006329,2010.0,77.727848
std,45.754781,32.620709,88.723103,3.511261,8.997166,0.0,9.377877
min,1.000000,1.000000,7.000000,1.700000,1.000000,2010.0,56.000000
25%,40.250000,18.000000,119.000000,7.400000,8.000000,2010.0,72.000000
50%,79.500000,30.500000,197.000000,9.700000,16.000000,2010.0,78.500000
75%,118.750000,61.500000,257.000000,11.875000,24.000000,2010.0,84.000000
max,158.000000,168.000000,334.000000,20.700000,31.000000,2010.0,97.000000

In [72]:
weather = weather.drop("Unnamed: 0", axis = 1)

In [73]:
weather["Year"].unique()

array([2010])

In [74]:
weather = weather.drop("Year",axis = 1)

In [75]:
weather = weather.drop("Temp C",axis = 1)

# two temp is there

In [76]:
weather.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Temp        0
Weather     3
dtype: int64

In [77]:
weather["Ozone"].mean()

np.float64(41.583333333333336)

In [78]:
weather["Ozone"] = weather["Ozone"].fillna(weather["Ozone"].mean())

In [79]:
weather.isna().sum()

Ozone      0
Solar.R    7
Wind       0
Month      0
Day        0
Temp       0
Weather    3
dtype: int64

In [80]:
weather["Solar.R"] = weather["Solar.R"].fillna(weather["Solar.R"].mean())

In [81]:
weather.isna().sum()

Ozone      0
Solar.R    0
Wind       0
Month      0
Day        0
Temp       0
Weather    3
dtype: int64

In [82]:
# Replace weather with mode - bez it is a categorical data

weather["Weather"] = weather["Weather"].fillna(weather["Weather"].mode()[0])

# [0] - because mode can return two values but fillna expects one value

In [83]:
weather.isna().sum()

Ozone      0
Solar.R    0
Wind       0
Month      0
Day        0
Temp       0
Weather    0
dtype: int64

In [84]:
weather.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month       object
Day          int64
Temp         int64
Weather     object
dtype: object

In [85]:
weather["Month"].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [86]:
weather["Month"] = weather["Month"].replace(to_replace="May",value= "5")

In [87]:
weather["Month"].unique()

array(['5', '6', '7', '8', '9'], dtype=object)

In [88]:
weather.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month       object
Day          int64
Temp         int64
Weather     object
dtype: object

In [89]:
weather["Month"] = pd.to_numeric(weather["Month"])

In [90]:
weather.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month        int64
Day          int64
Temp         int64
Weather     object
dtype: object

### For categorical data - obj to int

Label Encoding

One Hot encoding

In [91]:
# We go for label encoding

In [92]:
from sklearn.preprocessing import LabelEncoder

In [93]:
weather_1 = weather.copy()
weather_1

         Ozone     Solar.R  Wind  Month  Day  Temp Weather
0    41.000000  190.000000   7.4      5    1    67       S
1    36.000000  118.000000   8.0      5    2    72       C
2    12.000000  149.000000  12.6      5    3    74      PS
3    18.000000  313.000000  11.5      5    4    62       S
4    41.583333  185.403974  14.3      5    5    56       S
..         ...         ...   ...    ...  ...   ...     ...
153  41.000000  190.000000   7.4      5    1    67       C
154  30.000000  193.000000   6.9      9   26    70      PS
155  41.583333  145.000000  13.2      9   27    77       S
156  14.000000  191.000000  14.3      9   28    75       S
157  18.000000  131.000000   8.0      9   29    76       C

[158 rows x 7 columns]

In [94]:
le = LabelEncoder()

In [95]:
weather_1["Weather"] = le.fit_transform(weather_1["Weather"])

In [96]:
weather_1.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month        int64
Day          int64
Temp         int64
Weather      int64
dtype: object

In [97]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np #To use toarray

In [98]:
weather_2 = weather.copy()
weather_2

         Ozone     Solar.R  Wind  Month  Day  Temp Weather
0    41.000000  190.000000   7.4      5    1    67       S
1    36.000000  118.000000   8.0      5    2    72       C
2    12.000000  149.000000  12.6      5    3    74      PS
3    18.000000  313.000000  11.5      5    4    62       S
4    41.583333  185.403974  14.3      5    5    56       S
..         ...         ...   ...    ...  ...   ...     ...
153  41.000000  190.000000   7.4      5    1    67       C
154  30.000000  193.000000   6.9      9   26    70      PS
155  41.583333  145.000000  13.2      9   27    77       S
156  14.000000  191.000000  14.3      9   28    75       S
157  18.000000  131.000000   8.0      9   29    76       C

[158 rows x 7 columns]

In [99]:
OHE = OneHotEncoder()

In [100]:
weather_2["Weather"].unique()

array(['S', 'C', 'PS'], dtype=object)

In [101]:
weather_2[['S', 'C', 'PS']] = OHE.fit_transform(weather_2[["Weather"]]).toarray()

#

In [102]:
weather_2

         Ozone     Solar.R  Wind  Month  Day  Temp Weather    S    C   PS
0    41.000000  190.000000   7.4      5    1    67       S  0.0  0.0  1.0
1    36.000000  118.000000   8.0      5    2    72       C  1.0  0.0  0.0
2    12.000000  149.000000  12.6      5    3    74      PS  0.0  1.0  0.0
3    18.000000  313.000000  11.5      5    4    62       S  0.0  0.0  1.0
4    41.583333  185.403974  14.3      5    5    56       S  0.0  0.0  1.0
..         ...         ...   ...    ...  ...   ...     ...  ...  ...  ...
153  41.000000  190.000000   7.4      5    1    67       C  1.0  0.0  0.0
154  30.000000  193.000000   6.9      9   26    70      PS  0.0  1.0  0.0
155  41.583333  145.000000  13.2      9   27    77       S  0.0  0.0  1.0
156  14.000000  191.000000  14.3      9   28    75       S  0.0  0.0  1.0
157  18.000000  131.000000   8.0      9   29    76       C  1.0  0.0  0.0

[158 rows x 10 columns]

# Just for learning we used both model in copy of data
# We can proceed with original data - Label encoding

In [103]:
le = LabelEncoder()

In [104]:
weather["Weather"] = le.fit_transform(weather["Weather"])

In [105]:
weather.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month        int64
Day          int64
Temp         int64
Weather      int64
dtype: object

# x and y finding

In [106]:
x = weather.drop("Temp", axis = 1)
x

         Ozone     Solar.R  Wind  Month  Day  Weather
0    41.000000  190.000000   7.4      5    1        2
1    36.000000  118.000000   8.0      5    2        0
2    12.000000  149.000000  12.6      5    3        1
3    18.000000  313.000000  11.5      5    4        2
4    41.583333  185.403974  14.3      5    5        2
..         ...         ...   ...    ...  ...      ...
153  41.000000  190.000000   7.4      5    1        0
154  30.000000  193.000000   6.9      9   26        1
155  41.583333  145.000000  13.2      9   27        2
156  14.000000  191.000000  14.3      9   28        2
157  18.000000  131.000000   8.0      9   29        0

[158 rows x 6 columns]

In [107]:
y = weather[["Temp"]]
y

     Temp
0      67
1      72
2      74
3      62
4      56
..    ...
153    67
154    70
155    77
156    75
157    76

[158 rows x 1 columns]

In [108]:
from sklearn.model_selection import train_test_split

In [109]:
x_train, x_test, y_train, y_test = train_test_split(x,y, train_size= 0.80)

In [110]:
x_train.shape

(126, 6)

# Decision Tree model

In [118]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [137]:
model = DecisionTreeClassifier(max_depth=10)

In [138]:
model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10)

In [139]:
y_train_pred = model.predict(x_train)

In [140]:
y_test_pred = model.predict(x_test)

In [141]:
accuracy_score(y_train,y_train_pred)

0.9603174603174603

In [142]:
accuracy_score(y_test,y_test_pred)

C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:99: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_pred = type_of_target(y_pred, input_name="y_pred")

0.125